version: "3.9"
services:
    main_task:
        build: .
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /home/pi/.Xauthority:/root/.Xauthority:rw
            - ./src:/usr/src/app
        devices: 
            - "/dev:/dev"
        network_mode: "host"
        privileged: true
        command: python3 serve.py
